name: phageterm
channels:
  - conda-forge
  - defaults
dependencies:
  - Python=2.7
  - matplotlib=2.0.2
  - numpy=1.11
  - pandas=0.19.1
  - scikit-learn=0.18.1
  - scipy=0.19.0
  - statsmodels=0.8.0
  - reportlab=3.4.0